name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules : true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Add MSVC to PATH
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win64
      
    - name: Generate ARTIFACT_VERSION
      run: echo ARTIFACT_VERSION=$((Get-Date).tostring("yyyy.MMdd.HHmm")) >> $env:GITHUB_ENV
      
    - name: Configure cmake
      working-directory: ./sentry-native
      run: cmake -B build 
      
    - name: Build 
      working-directory: ./sentry-native
      run: cmake --build build --config RelWithDebInfo
      
    - name: Install
      working-directory: ./sentry-native
      run: cmake --install build --prefix install --config RelWithDebInfo

    - name: Pack NuGet (Package)
      run: nuget pack sentry-clarity.nuspec -p version=$env:ARTIFACT_VERSION

    - name: Publish NuGet
      if: github.event_name != 'pull_request'
      run: |
        nuget sources Add -Name github -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -Username ${{github.repository_owner}} -Password ${{github.token}}
        nuget push *.nupkg -Source github -SkipDuplicate -ApiKey ${{github.token}}
